# Generated by Django 5.1.4 on 2025-01-16 21:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACK_OFFICE', '0002_plugin_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='installed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
